server:
    port: 8888

# upload path
upload:
    path: blogFile/

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.100.95.1:3306/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: dev
        password: dev@dev
        driver-class-name: com.mysql.cj.jdbc.Driver

        druid:
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: SELECT 'x'
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            use-global-data-source-stat: true
            filter:
                stat:
                    merge-sql: true
                    log-slow-sql: true
                    slow-sql-millis: 10000
            stat-view-servlet:
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        open-in-view: true

    cache:
        ehcache:
            config: classpath:ehcache.xml

    redis:
        database: 0
        host: 47.100.95.1
        port: 6379
        password:
        timeout: 10000
#        lettuce:
#            pool:
#                max-active: 8
#                max-wait: -1
#                max-idle: 8
#                min-idle: 0
    data:
        redis:
            repositories:
                enabled: false

logging:
    config: classpath:log4j2-spring.xml